// Public ABI of the pinned libamdf provider.
#include "amdf/amdf.h"
#include "amdf/gpu.h"
#include "amdf/xdna.h"

// Give bindgen typed names for public macros containing C casts.
enum {
    HRX_AMDF_ABI_VERSION = AMDF_ABI_VERSION_LATEST,
    HRX_AMDF_STRUCTURE_TYPE_GPU_ENDPOINT_INFO = AMDF_STRUCTURE_TYPE_GPU_ENDPOINT_INFO,
    HRX_AMDF_STRUCTURE_TYPE_GPU_DEVICE_CREATE_INFO = AMDF_STRUCTURE_TYPE_GPU_DEVICE_CREATE_INFO,
    HRX_AMDF_STRUCTURE_TYPE_GPU_DEVICE_INFO = AMDF_STRUCTURE_TYPE_GPU_DEVICE_INFO,
    HRX_AMDF_STRUCTURE_TYPE_GPU_KERNEL_QUEUE_CREATE_INFO = AMDF_STRUCTURE_TYPE_GPU_KERNEL_QUEUE_CREATE_INFO,
    HRX_AMDF_STRUCTURE_TYPE_GPU_KERNEL_QUEUE_SUBMISSION_INFO = AMDF_STRUCTURE_TYPE_GPU_KERNEL_QUEUE_SUBMISSION_INFO,
    HRX_AMDF_STRUCTURE_TYPE_GPU_USER_QUEUE_CREATE_INFO = AMDF_STRUCTURE_TYPE_GPU_USER_QUEUE_CREATE_INFO,
    HRX_AMDF_STRUCTURE_TYPE_XDNA_ENDPOINT_INFO = AMDF_STRUCTURE_TYPE_XDNA_ENDPOINT_INFO,
    HRX_AMDF_STRUCTURE_TYPE_XDNA_DEVICE_CREATE_INFO = AMDF_STRUCTURE_TYPE_XDNA_DEVICE_CREATE_INFO,
    HRX_AMDF_STRUCTURE_TYPE_XDNA_DEVICE_INFO = AMDF_STRUCTURE_TYPE_XDNA_DEVICE_INFO,
    HRX_AMDF_STRUCTURE_TYPE_XDNA_KERNEL_QUEUE_CREATE_INFO = AMDF_STRUCTURE_TYPE_XDNA_KERNEL_QUEUE_CREATE_INFO,
    HRX_AMDF_STRUCTURE_TYPE_XDNA_KERNEL_QUEUE_SUBMISSION_INFO = AMDF_STRUCTURE_TYPE_XDNA_KERNEL_QUEUE_SUBMISSION_INFO,
    HRX_AMDF_STRUCTURE_TYPE_XDNA_CONTEXT_CREATE_INFO = AMDF_STRUCTURE_TYPE_XDNA_CONTEXT_CREATE_INFO,
    HRX_AMDF_STRUCTURE_TYPE_XDNA_CONTEXT_INFO = AMDF_STRUCTURE_TYPE_XDNA_CONTEXT_INFO,
    HRX_AMDF_STRUCTURE_TYPE_XDNA_CONTEXT_PLACEMENT_INFO = AMDF_STRUCTURE_TYPE_XDNA_CONTEXT_PLACEMENT_INFO,
};
